version: "3"
services:
  api-local:
    build:
      dockerfile: ./Dockerfile.local
    # command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - "/usr/src:/src"
    env_file:
      - .env
